# Default initial positions for my_ur5e's ros2_control fake system

initial_positions:
  elbow_joint: 0.0
  wrist_1_joint: 0.0
  wrist_2_joint: 0.0
  wrist_3_joint: 0.0
  shoulder_lift_joint: 3.14
  shoulder_pan_joint: 0.0

